### ISSUE TITLE
please add and fix bug

### ISSUE THREAD

**Issue by DarknessGaming** [xXSirGamesXx/SkyblockPE#10]
Maybe you can add random block thay thế cho random item
 
 You can fix bug on Player use command and crash for use /sb create, I use it server is stop

  Don't use §l for message help

**Comment by xXSirGamesXx** [comment]
Ill change the help look. Can you elaborate the first part more though.

**Comment by xXSirGamesXx** [comment]
Im having no issues with players creating islands, download the latest phar from the versions folder
