### ISSUE TITLE
Reload/restart = lost island

### ISSUE THREAD

**Issue by optimusprime338** [xXSirGamesXx/SkyblockPE#7]
after reload or restart it says you dont have a island and also when trying to create new it says you already got a island . and also this warning is giving up in console on reload or restart:-
WARNING Could not load block in level Sky Block because that level is not loaded.

**Comment by xXSirGamesXx** [comment]
Its working fine for me.
Try reinstalling the plugin config file and deleting the world. It should be something like this a1498188765-7738 as the name of the world.

**Comment by optimusprime338** [comment]
I did many times but its not happening .. have some problem in level loading..

**Comment by xXSirGamesXx** [comment]
Hmm

**Comment by optimusprime338** [comment]
nvm solved it

**Comment by optimusprime338** [comment]
actully if u reload player have to rejoin game or just restart
