### ISSUE TITLE
Normal players

### ISSUE THREAD

**Issue by optimusprime338** [xXSirGamesXx/SkyblockPE#8]
Normal players cant create or join skyblock .. the command is not working for them

**Comment by xXSirGamesXx** [comment]
Ill look into it

**Comment by DarknessGaming** [comment]
Player can't use /sb help

**Comment by xXSirGamesXx** [comment]
I think i might have corrupted the phar.

**Comment by optimusprime338** [comment]
No it's working ..use perms :- sbpe.cmd.{Command}

**Comment by xXSirGamesXx** [comment]
Oh, i didnt corectly implement permisssions.

**Comment by xXSirGamesXx** [comment]
I have to register the permissions in plugin.yml too, give me some time.

**Comment by optimusprime338** [comment]
Ok sure thanks

**Comment by DarknessGaming** [comment]
Hey pls edit island small, island now very big

**Comment by DarknessGaming** [comment]
Hey pls edit island small, island now very big

**Comment by DarknessGaming** [comment]
Hey pls edit island small, island now very big

**Comment by DarknessGaming** [comment]
Hey pls edit island small, island now very big

**Comment by DarknessGaming** [comment]
Hey pls edit island small, island now very big

**Comment by DarknessGaming** [comment]
Hey pls edit island small, island now very big

**Comment by DarknessGaming** [comment]
And i can't open chet on island, open is bug and server is stop

**Comment by xXSirGamesXx** [comment]
Do you speak another languagae?

**Comment by xXSirGamesXx** [comment]
Whats your server?

**Comment by optimusprime338** [comment]
Use manyworlds plugin.  And then restart server

**Comment by xXSirGamesXx** [comment]
^

**Comment by xXSirGamesXx** [comment]
I've registered the permissions and added a defaullt permission; "sbpe"

**Comment by optimusprime338** [comment]
Thanks:)

**Comment by xXSirGamesXx** [comment]
Dont use it yet though.

**Comment by xXSirGamesXx** [comment]
Wait for me to release bc i messed some thing up in the plugin.yml

**Comment by xXSirGamesXx** [comment]
I see the issue, im op.

**Comment by optimusprime338** [comment]
just need to copy and paste these perms:-
  - sbpe.cmd.accept
  - sbpe.cmd.create
  - sbpe.cmd.expel
  - sbpe.cmd.help
  - sbpe.cmd.home
  - sbpe.cmd.invite
  - sbpe.cmd.join
  - sbpe.cmd.leave
  - sbpe.cmd.lock
  - sbpe.cmd.makeleader
  - sbpe.cmd.members
  - sbpe.cmd.reject
  - sbpe.cmd.remove
  - sbpe.cmd.sethome

**Comment by xXSirGamesXx** [comment]
I still havent implemented it correctly xD

**Comment by optimusprime338** [comment]
Ohh dang XD

**Comment by optimusprime338** [comment]
can you check /skyblock remove command .. players want to delete islands but cant.. and cant share too they should be able to share after having island too
